"""Add event store schemas

Revision ID: 1a6e5f280982
Revises: 
Create Date: 2026-02-19 09:42:35.958735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6e5f280982'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features_daily',
    sa.Column('feature_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('feature_id')
    )
    op.create_index('ix_features_symbol_date', 'features_daily', ['symbol', 'date'], unique=True)
    op.create_table('learning_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('model_registry',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('model_version',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version_tag', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('hyperparams_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('ix_model_version_status', 'model_version', ['status'], unique=False)
    op.create_index('ix_model_version_type_tag', 'model_version', ['model_type', 'version_tag'], unique=True)
    op.create_table('news_article',
    sa.Column('article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_reason', sa.String(length=50), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('embedding_vector', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_news_article_cluster_id', 'news_article', ['cluster_id'], unique=False)
    op.create_index('ix_news_article_content_hash', 'news_article', ['content_hash'], unique=False)
    op.create_index('ix_news_article_published_at', 'news_article', ['published_at'], unique=False)
    op.create_table('news_raw',
    sa.Column('news_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('news_id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('ticker',
    sa.Column('ticker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ticker_id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_ticker_symbol', 'ticker', ['symbol'], unique=False)
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.article_id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.ticker_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_event_detected_at', 'event', ['detected_at'], unique=False)
    op.create_index('ix_event_ticker_type', 'event', ['ticker_id', 'event_type'], unique=False)
    op.create_table('news_enriched',
    sa.Column('enriched_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_tags', sa.Text(), nullable=True),
    sa.Column('symbols', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_raw.news_id'], ),
    sa.PrimaryKeyConstraint('enriched_id')
    )
    op.create_table('news_mention',
    sa.Column('mention_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.article_id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.ticker_id'], ),
    sa.PrimaryKeyConstraint('mention_id')
    )
    op.create_index('ix_news_mention_article_ticker', 'news_mention', ['article_id', 'ticker_id'], unique=True)
    op.create_index('ix_news_mention_ticker', 'news_mention', ['ticker_id'], unique=False)
    op.create_table('prediction',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('prediction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_horizon_days', sa.Integer(), nullable=False),
    sa.Column('predicted_return', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('coverage_level', sa.Float(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.version_id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.ticker_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('ix_prediction_model_ticker', 'prediction', ['model_version_id', 'ticker_id'], unique=False)
    op.create_index('ix_prediction_ticker_date', 'prediction', ['ticker_id', 'prediction_date'], unique=False)
    op.create_table('premarket_plan',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=True),
    sa.Column('rank_model_id', sa.Integer(), nullable=True),
    sa.Column('simulation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rank_model_id'], ['model_registry.model_id'], ),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('plan_date')
    )
    op.create_table('price_bar',
    sa.Column('bar_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.ticker_id'], ),
    sa.PrimaryKeyConstraint('bar_id')
    )
    op.create_index('ix_price_bar_ticker_interval_ts', 'price_bar', ['ticker_id', 'interval', 'timestamp'], unique=True)
    op.create_index('ix_price_bar_ticker_ts', 'price_bar', ['ticker_id', 'timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['premarket_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('alert_id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_alerts_dedupe', 'alerts', ['dedupe_key'], unique=False)
    op.create_index('ix_alerts_symbol_ts', 'alerts', ['symbol', 'created_at'], unique=False)
    op.create_table('event_argument',
    sa.Column('arg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('arg_name', sa.String(length=50), nullable=False),
    sa.Column('arg_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('arg_id')
    )
    op.create_index('ix_event_argument_event_id', 'event_argument', ['event_id'], unique=False)
    op.create_table('event_impact',
    sa.Column('impact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('abnormal_return_1d', sa.Float(), nullable=True),
    sa.Column('abnormal_return_5d', sa.Float(), nullable=True),
    sa.Column('abnormal_return_20d', sa.Float(), nullable=True),
    sa.Column('volume_spike', sa.Float(), nullable=True),
    sa.Column('volatility_spike', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('impact_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_event_impact_event_id', 'event_impact', ['event_id'], unique=False)
    op.create_table('fills',
    sa.Column('fill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['premarket_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('fill_id')
    )
    op.create_index('ix_fills_symbol_ts', 'fills', ['symbol', 'ts'], unique=False)
    op.create_table('plan_trades',
    sa.Column('trade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('risk_per_share', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('trigger_json', sa.Text(), nullable=True),
    sa.Column('do_not_trade_if', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['premarket_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index('ix_plan_trades_plan_symbol', 'plan_trades', ['plan_id', 'symbol'], unique=False)
    op.create_table('trade_outcomes',
    sa.Column('outcome_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('holding_seconds', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['plan_trades.trade_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    op.create_index('ix_outcomes_symbol_ts', 'trade_outcomes', ['symbol', 'created_at'], unique=False)
    op.create_table('failure_labels',
    sa.Column('label_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outcome_id'], ['trade_outcomes.outcome_id'], ),
    sa.PrimaryKeyConstraint('label_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure_labels')
    op.drop_index('ix_outcomes_symbol_ts', table_name='trade_outcomes')
    op.drop_table('trade_outcomes')
    op.drop_index('ix_plan_trades_plan_symbol', table_name='plan_trades')
    op.drop_table('plan_trades')
    op.drop_index('ix_fills_symbol_ts', table_name='fills')
    op.drop_table('fills')
    op.drop_index('ix_event_impact_event_id', table_name='event_impact')
    op.drop_table('event_impact')
    op.drop_index('ix_event_argument_event_id', table_name='event_argument')
    op.drop_table('event_argument')
    op.drop_index('ix_alerts_symbol_ts', table_name='alerts')
    op.drop_index('ix_alerts_dedupe', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_price_bar_ticker_ts', table_name='price_bar')
    op.drop_index('ix_price_bar_ticker_interval_ts', table_name='price_bar')
    op.drop_table('price_bar')
    op.drop_table('premarket_plan')
    op.drop_index('ix_prediction_ticker_date', table_name='prediction')
    op.drop_index('ix_prediction_model_ticker', table_name='prediction')
    op.drop_table('prediction')
    op.drop_index('ix_news_mention_ticker', table_name='news_mention')
    op.drop_index('ix_news_mention_article_ticker', table_name='news_mention')
    op.drop_table('news_mention')
    op.drop_table('news_enriched')
    op.drop_index('ix_event_ticker_type', table_name='event')
    op.drop_index('ix_event_detected_at', table_name='event')
    op.drop_table('event')
    op.drop_index('ix_ticker_symbol', table_name='ticker')
    op.drop_table('ticker')
    op.drop_table('news_raw')
    op.drop_index('ix_news_article_published_at', table_name='news_article')
    op.drop_index('ix_news_article_content_hash', table_name='news_article')
    op.drop_index('ix_news_article_cluster_id', table_name='news_article')
    op.drop_table('news_article')
    op.drop_index('ix_model_version_type_tag', table_name='model_version')
    op.drop_index('ix_model_version_status', table_name='model_version')
    op.drop_table('model_version')
    op.drop_table('model_registry')
    op.drop_table('learning_runs')
    op.drop_index('ix_features_symbol_date', table_name='features_daily')
    op.drop_table('features_daily')
    # ### end Alembic commands ###
