"""Expert aggregator for running multiple experts and combining signals."""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from spectraquant.experts.base import BaseExpert
from spectraquant.experts.trend import TrendExpert
from spectraquant.experts.momentum import MomentumExpert
from spectraquant.experts.mean_reversion import MeanReversionExpert
from spectraquant.experts.volatility import VolatilityExpert
from spectraquant.experts.value import ValueExpert
from spectraquant.experts.news_catalyst import NewsCatalystExpert

logger = logging.getLogger(__name__)


EXPERT_REGISTRY = {
    "trend": TrendExpert,
    "momentum": MomentumExpert,
    "mean_reversion": MeanReversionExpert,
    "volatility": VolatilityExpert,
    "value": ValueExpert,
    "news_catalyst": NewsCatalystExpert,
}


def run_experts(
    config: dict,
    prices: pd.DataFrame,
    features: pd.DataFrame | None = None,
    news_data: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """Run all enabled experts and aggregate their signals.
    
    Args:
        config: Full configuration dict
        prices: DataFrame with OHLCV data
        features: Optional precomputed features
        news_data: Optional news data for news_catalyst expert
        
    Returns:
        DataFrame with columns: ticker, action, score, reason, expert, timestamp
    """
    experts_cfg = config.get("experts", {})
    
    if not experts_cfg.get("enabled", False):
        logger.info("Experts disabled; returning empty DataFrame")
        return pd.DataFrame(columns=["ticker", "action", "score", "reason", "expert", "timestamp"])
    
    expert_list = experts_cfg.get("list", [])
    min_coverage = experts_cfg.get("min_coverage", 5)
    
    if not expert_list:
        logger.warning("No experts configured in experts.list")
        return pd.DataFrame(columns=["ticker", "action", "score", "reason", "expert", "timestamp"])
    
    # Initialize experts
    experts: list[BaseExpert] = []
    for expert_name in expert_list:
        if expert_name not in EXPERT_REGISTRY:
            logger.warning("Unknown expert: %s", expert_name)
            continue
        
        try:
            expert_class = EXPERT_REGISTRY[expert_name]
            expert = expert_class(config)
            experts.append(expert)
            logger.info("Initialized expert: %s", expert_name)
        except Exception as e:
            logger.error("Failed to initialize expert %s: %s", expert_name, e)
    
    if not experts:
        logger.warning("No experts successfully initialized")
        return pd.DataFrame(columns=["ticker", "action", "score", "reason", "expert", "timestamp"])
    
    # Run each expert
    all_signals = []
    for expert in experts:
        try:
            logger.info("Running expert: %s", expert.name)
            signals = expert.generate_signals(prices, features, news_data)
            logger.info("Expert %s generated %d signals", expert.name, len(signals))
            
            # Convert to DataFrame
            df = expert.to_dataframe(signals)
            all_signals.append(df)
        except Exception as e:
            logger.error("Error running expert %s: %s", expert.name, e)
    
    if not all_signals:
        logger.warning("No signals generated by any expert")
        return pd.DataFrame(columns=["ticker", "action", "score", "reason", "expert", "timestamp"])
    
    # Combine all signals
    combined = pd.concat(all_signals, ignore_index=True)
    
    # Filter tickers with insufficient coverage
    ticker_coverage = combined.groupby("ticker").size()
    valid_tickers = ticker_coverage[ticker_coverage >= min_coverage].index.tolist()
    
    if valid_tickers:
        filtered_count = len(combined) - len(combined[combined["ticker"].isin(valid_tickers)])
        if filtered_count > 0:
            logger.info("Filtered out %d signals from %d tickers with insufficient expert coverage (< %d experts)",
                       filtered_count, len(ticker_coverage) - len(valid_tickers), min_coverage)
        combined = combined[combined["ticker"].isin(valid_tickers)]
        logger.info("Kept %d tickers with >= %d expert coverage", len(valid_tickers), min_coverage)
    
    # Write output
    output_dir = Path(experts_cfg.get("output_dir", "reports/experts"))
    output_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    output_file = output_dir / f"expert_signals_{timestamp}.csv"
    combined.to_csv(output_file, index=False)
    logger.info("Wrote %d expert signals to %s", len(combined), output_file)
    
    return combined
